### ISSUE TITLE
updating the gauge causes animation to start over

### ISSUE THREAD

**Issue by ilgrank** [Mictronics/GaugeMeter#10]
Hi
Thanks for the nice gauge!
a cosmetic issue, but when I set the gauge to say, 70% and then a background process updates it to, say, 73%, the gauge animation re-draws it from 0 to 73%, which is not that nice to see.
Any workaround?

**Comment by Mictronics** [comment]
This animation is intentionally. To stop animation set `data-animationstep` to 0.

**Comment by ilgrank** [comment]
Hi
thanks for the replay
I don't doubt it is intentional, but in a world of real-time background updates, it is not nice to have the graph redrawn from 0 to every update, nor to have it change abruprly (data-animationstep set to 0) when it happens.
Just my 2 cents :)
Thanks

**Comment by Mictronics** [comment]
Feel free to make a PR with the update behavior you expect to see.
