### ISSUE TITLE
how to sensor update  gauge esp32  8266 ? i am new to html

### ISSUE THREAD

**Issue by KARTHICKROBO** [Mictronics/GaugeMeter#11]
great job thanks at first for the great project .......

i am trying to include sensor data in gauge
using esp32 

i am able to  do in google metter ! example 

!DOCTYPE HTML><html>
  <head>
   <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>  
  <script type="text/javascript">
      google.charts.load('current', {'packages':['gauge']});
      google.charts.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Label', 'Value'],
          ['Memory', 0],
          ['CPU', 0],
          ['Network',0]
                    
        ]);

        var options = {
          width: 1500, height: 750,
          redFrom: 90, redTo: 1000,
          yellowFrom:75, yellowTo: 90,
          minorTicks: 50
        };

        var chart = new google.visualization.Gauge(document.getElementById('chart_div'));

        chart.draw(data, options);

        setInterval(function() 
        
        {  
   var xhttp = new XMLHttpRequest();
   xhttp.onreadystatechange = function() 
{  
    if (this.readyState == 4 && this.status == 200) 
    {      
      var volt = (( parseFloat(this.responseText)/ 4023)*100)
      data.setValue(0, 1, volt );
      chart.draw(data, options);
    }
}
        
  xhttp.open("GET", "/readABC", true);
  xhttp.send();
         
        } ,100);

 </script>
  </head>
  <body>
    <div id="chart_div" style="width: 400px; height: 120px;"></div>
  </body>
</html>

but i am unable to lode external data to  your  gauge ?

pls guide me 

i am beginner  only 

thanks in advance

**Comment by Mictronics** [comment]
doc.html from this repo shows all examples how to use the gauge.
I have no idea about "esp32" and your example refers something from Google that has no relation to my repo.

**Comment by KARTHICKROBO** [comment]
i find way out thank for the  design   

have a good day

**Comment by KARTHICKROBO** [comment]
thanks for help very easy ......

https://www.youtube.com/watch?v=-YnE1PxDwh0
