### ISSUE TITLE
Who to set metter over 230% or over 500 range ?

### ISSUE THREAD

**Issue by KARTHICKROBO** [Mictronics/GaugeMeter#12]
Its me again i am thankful to u 👏👏👏👏👍👍👍💯💯

I am desining sensor network

I am unable to set metter value over 100 % 

I need to display 230 volt ac in metter 

And 2000 c temperature

Pls help thanks in advance 👏👏👏

I am new to web design   ..,...👍👍👍✊

**Comment by KARTHICKROBO** [comment]
Data total fix the issue ??? If i put 500 metter range from ,0 to 500??

**Comment by Mictronics** [comment]
See very last example in doc.html.

```
data-percent:              0
data-total:                250
data-used:                 230
```

For max 250V and 230V indicating

**Comment by KARTHICKROBO** [comment]
thanks but i unable display over 100%  it stops at 100

i need to display 230 ++

![Screenshot (1)](https://user-images.githubusercontent.com/31999135/89116658-411f6600-d4b4-11ea-8ef5-8d6d23284980.png)

**Comment by Mictronics** [comment]
```
<div class="GaugeMeter" id="GaugeMeter_94" data-label="Main" data-append="V" data-size="180" data-theme="Black" data-width="7" data-animate_gauge_colors=false data-animate_text_colors=false data-style="Arch" data-label_color="#FF0000" data-showvalue=true data-total=250 data-used=223></div>
```
![image](https://user-images.githubusercontent.com/11965780/89118354-6f497980-d4a5-11ea-90dd-259745881294.png)

You may share your code on jsfiddle so I can assist if needed.

**Comment by KARTHICKROBO** [comment]
thanks  one again for fast replay it working  now

**Comment by KARTHICKROBO** [comment]
thanks  

![Screenshot (2)](https://user-images.githubusercontent.com/31999135/89119318-36bc9680-d4cb-11ea-9e71-6f9f0ffd4f99.png)
