### ISSUE TITLE
unable to display float value and for float value meter not updating .....

### ISSUE THREAD

**Issue by KARTHICKROBO** [Mictronics/GaugeMeter#13]
i tried all day to solve my self 

but i can't 

for float value mette  move and not updating  and showing (..........)    

![Screenshot (4)](https://user-images.githubusercontent.com/31999135/89209606-47106680-d5dc-11ea-8d99-bcbd5f6fd3be.png)
![Screenshot (5)](https://user-images.githubusercontent.com/31999135/89209643-542d5580-d5dc-11ea-8834-5ee62d208d75.png)

**Comment by Mictronics** [comment]
Gauges will accept only integer values.

**Comment by KARTHICKROBO** [comment]
solved  after edit in js   

is it correct ? ????????????????????????????????????  work ???????
 
and edit font size to   30+"px"
after 

 if(Number.parseFloat(option.used) && Number.parseFloat(option.total))
            
            
            {

                
               var u = option.used;

                var t = option.total;





![Screenshot (6)](https://user-images.githubusercontent.com/31999135/89255206-c46cc300-d63e-11ea-9785-b8732ce61865.png)

**Comment by Mictronics** [comment]
Seems to work. But I'm not sure why you need fractions when dealing kiloWatts or several hundred Volts.

**Comment by KARTHICKROBO** [comment]
for low volt i need it 24 volt solar and battery etc
