### ISSUE TITLE
Dynamically change percentage without restarting gauge animation

### ISSUE THREAD

**Issue by kikanshathomas** [Mictronics/GaugeMeter#14]
I would like to use this gauge as a health gauge for my FiveM server. I can not get it to update the percentage dynamically without having to reload the gauge. Is this possible to do this?

**Comment by Mictronics** [comment]
Update the gauge like: ` $("#GaugeMeter_1").gaugeMeter({percent:15});`

**Comment by Mictronics** [comment]
Stale.
