### ISSUE TITLE
Recreate demo gauge

### ISSUE THREAD

**Issue by Amplificator** [Mictronics/GaugeMeter#15]
If I want to recreate the "1.21 GW" gauge from the demo image, what settings would I need to use then?

**Comment by Mictronics** [comment]
`<div class="GaugeMeter" id="GaugeMeter_105" data-text="1.2" data-label="Mr. Fusion" data-size="150" data-style="Semi" data-width="15" data-showvalue="false" data-min=0 data-total=5 data-used=1 data-append="GW"></div>`
Changing the gauge indication works only with integer values in `data-used`, hence round the float. At the same time change `data-text``to indicate the float value as string.

**Comment by Amplificator** [comment]
I cannot recreate the gauge using just what you posted - it's just blank?

**Comment by Mictronics** [comment]
Do you initialize the gauge via jQuery JS?
The demo.html has an example with the code I posted above. Search for "GaugeMeter_105".
