### ISSUE TITLE
data-animate_text_colors=true is not working

### ISSUE THREAD

**Issue by GianmariaPrevitera** [Mictronics/GaugeMeter#16]
when data-animate_text_colors=true is used the animation does not start, it remains at the fixed point of the value. Even if you use the jquery or if you use the data-percent="value"

**Comment by Mictronics** [comment]
See doc.html:
```
<div class="GaugeMeter" id="GaugeMeter_81" data-percent="20" data-append="%" data-size="150" data-theme="Red-Gold-Green" data-animate_gauge_colors=true data-animate_text_colors=true></div>
<div class="GaugeMeter" id="GaugeMeter_82" data-percent="40" data-append="%" data-size="150" data-theme="Red-Gold-Green" data-animate_gauge_colors=true data-animate_text_colors=true></div>
<div class="GaugeMeter" id="GaugeMeter_83" data-percent="60" data-append="%" data-size="150" data-theme="Red-Gold-Green" data-animate_gauge_colors=true data-animate_text_colors=true></div>
<div class="GaugeMeter" id="GaugeMeter_84" data-percent="80" data-append="%" data-size="150" data-theme="Red-Gold-Green" data-animate_gauge_colors=true data-animate_text_colors=true></div>
<div class="GaugeMeter" id="GaugeMeter_85" data-percent="100" data-append="%" data-size="150" data-theme="Red-Gold-Green" data-animate_gauge_colors=true data-animate_text_colors=true></div>
```
You may provide the tag line so I can debug myself.

**Comment by GianmariaPrevitera** [comment]
in your doc.html the circe animation appears (I downloaded a fresh one version to make sure that it was not an importing problem) but the text animation (like in the original version) does not. it appears as a static value and not "changing" the value growing until it reaches the final value. (I'm talking numbers only, the circle animation works fine!)
no errors appears in the console
Thanks for your job.

**Comment by Mictronics** [comment]
Understood. What you expect is an up counting value, like the circle is growing until its final value, right?
In that case your expectation is wrong. `data-animate_text_colors=true` means that the text color is changing with the circle color. e.g. in the demo, red for low numbers and green for high numbers.
There is no animation of the value itself, like slow counting etc.

**Comment by GianmariaPrevitera** [comment]
Tnx, so how can I obtain the intended animation like it was in the origial version? is it a function removed for other purposes?

**Comment by Mictronics** [comment]
In fact, I'm not aware that there was such function in the original code. As far as I remember I have nothing deleted on purpose. Need to check...

**Comment by GianmariaPrevitera** [comment]
if you need you can find old version that has the function that I talking about in that site:
https://www.jqueryscript.net/demo/Customizable-Animated-jQuery-HTML5-Gauge-Meter-Plugin/
it should be near the code you originally used, but I cannot use it for my purpose (the javascript present a bug that creare a double circle). I hope being useful enought.

**Comment by Mictronics** [comment]
Found an old code version. Seems I have changed the code significantly. The numerical value indication is generated and drawn prior to the arc/circle. To restore the numerical animation the code has to be changed in a way that the value is generated and drawn together with the arc/circle in each animation step.
Fully understand the problem, will look into that.

**Comment by webprom** [comment]
Would be great if you add back the counting numbers option too. Thanks!

**Comment by Mictronics** [comment]
> Would be great if you add back the counting numbers option too. Thanks!

Check last commit. Counting should work now depending on the given options.
Feedback welcome. Close PR when you thinks it's fixed.

**Comment by webprom** [comment]
@Mictronics Great! It works!
Thank you!

**Comment by Mictronics** [comment]
Fixed.
