### ISSUE TITLE
update gauge using data-used

### ISSUE THREAD

**Issue by paonza** [Mictronics/GaugeMeter#17]
Hi,
I'm using the following gauge:
`<div
          class='GaugeMeter'
          id='pv_power_1'
          data-percent='0'
          data-min='0'
          data-total='4200'
          data-used='1200'
          data-showvalue='true'
          data-append='W'
          data-size='200'
          data-theme='LightBlue-DarkBlue'
          data-back='RGBa(0,0,0,.1)'
          data-animate_gauge_colors='true'
          data-animate_text_colors='true'
          data-width='15'
          data-label='PV1 Power'
          data-style='Arch'
          data-label_color='#999'
        ></div>`

both the following update command doesn't works....
$('#pv_power_1').gaugeMeter({used:1000});
or
$('#pv_power_1').attr('data-used','1000').gaugeMeter({percent:0});

how can dynamically update this gauge?
thank you!

**Comment by Mictronics** [comment]
`$('#pv_power_1').data('used', parseInt('1000', 10)).gaugeMeter();` or `$('#pv_power_1').data('used', 1000).gaugeMeter();`
Make sure the value given for key 'used' is of type number.
