### ISSUE TITLE
Problems with running on IOS / Safari Browser

### ISSUE THREAD

**Issue by nobby2k** [Mictronics/GaugeMeter#18]
Hello, 
at first a great Thanks to you for sharing your work.
I have implemented this on my page and it work without problems if i use browsers like CHROME, IE, FIREFOX.
But on my mobile devices ( Iphone or Ipad with actual IOS Version) , i see no reaction. The gauge bar also than the text does not appear.
Do you have an idea what could cause this problem ?

Thanks for help.

**Comment by Mictronics** [comment]
No instant idea. I have no access to Apple devices, so can't try. Do you depend on jQuery on your page?
You may try the non-jQuery version: https://github.com/Mictronics/gaugemeter-ts

**Comment by nobby2k** [comment]
Hello,
very thanks for the reply. If i've seen right, you come from Germany.
I'm from Germany too, so perhaps, when its ok for you, i will you ask another question in german.

Ich habe mir deinen link angeschaut aber bin nicht ganz schlau geworden. Im GH Verzeichnis liegen ja drei Files , einmal das" GaugeMeter.js", dann das "GaugeMeter.js.map" und dann noch das "GaugeMeter.ts". Da ich kein Profi auf dem Gebiet bin und schon vor einiger Zeit dein Repo entdeckt und damit getestet hatte, muss ich zugeben, dass
es mir nicht klar wird, welches File ich nun verwenden soll.

Kannst du mir da nochmal Hilfestellung geben.
Wäre super nett.
Danke Dir.
Gruß Norbert
________________________________
Von: Mictronics ***@***.***>
Gesendet: Dienstag, 14. Mai 2024 19:51 Uhr
An: Mictronics/GaugeMeter ***@***.***>
Cc: nobby2k ***@***.***>; Author ***@***.***>
Betreff: Re: [Mictronics/GaugeMeter] Problems with running on IOS / Safari Browser (Issue #18)


No instant idea. I have no access to Apple devices, so can't try. Do you depend on jQuery on your page?
You may try the non-jQuery version: https://github.com/Mictronics/gaugemeter-ts

**Comment by nobby2k** [comment]
Hallo nochmal,

wollte nur Bescheid geben, dass ich es hinbekommen habe.
Habe das .js file und das .js.map file implementiert und tatsächlich läuft das jetzt auch auf Safari /  Apple IOS.

Vielen Dank.
Gruß Norbert
________________________________
Von: Norbert Schär ***@***.***>
Gesendet: Dienstag, 14. Mai 2024 21:36 Uhr
An: Mictronics/GaugeMeter ***@***.***>
Betreff: AW: [Mictronics/GaugeMeter] Problems with running on IOS / Safari Browser (Issue #18)

Hello,
very thanks for the reply. If i've seen right, you come from Germany.
I'm from Germany too, so perhaps, when its ok for you, i will you ask another question in german.

Ich habe mir deinen link angeschaut aber bin nicht ganz schlau geworden. Im GH Verzeichnis liegen ja drei Files , einmal das" GaugeMeter.js", dann das "GaugeMeter.js.map" und dann noch das "GaugeMeter.ts". Da ich kein Profi auf dem Gebiet bin und schon vor einiger Zeit dein Repo entdeckt und damit getestet hatte, muss ich zugeben, dass
es mir nicht klar wird, welches File ich nun verwenden soll.

Kannst du mir da nochmal Hilfestellung geben.
Wäre super nett.
Danke Dir.
Gruß Norbert
________________________________
Von: Mictronics ***@***.***>
Gesendet: Dienstag, 14. Mai 2024 19:51 Uhr
An: Mictronics/GaugeMeter ***@***.***>
Cc: nobby2k ***@***.***>; Author ***@***.***>
Betreff: Re: [Mictronics/GaugeMeter] Problems with running on IOS / Safari Browser (Issue #18)


No instant idea. I have no access to Apple devices, so can't try. Do you depend on jQuery on your page?
You may try the non-jQuery version: https://github.com/Mictronics/gaugemeter-ts

**Comment by nobby2k** [comment]
Hallo,

muss nun doch nochmal stören.
Ich hatte ja dein anderes GaugeMeter JQUERY Script am laufen, nur dass es eben nicht auf IOS / Safari funktionierte.

Ich musste es für meine Anwendung (Simulation eines Drehzahlmessers ) so ändern, dass man keinen prozent-Wert bzw. überhaupt gar keine Text oder numerischen Darstellungen sieht. Hatte dazu einfach an den entsprechenden Stellen als Color dann "transparent" eingetragen und es hat funktioniert.

mit der neuen Variante bekomme ich das einfach nicht hin. Es wird einfach immer ein Zahlenwert angezeigt der sogar mit der Funktion animated_label_color seine Farbe entsprechend ändert, obwohl ich dies ja durch die Deklaration explizit deaktiviert habe.

Ich denke ( entschuldige bitte falls ich total falsch liege) dass dies etwas mit der Funktion zum Updaten des Wertes zu tun hat.
ich habe diese nach deinen Vorgaben umgesetzt, aber mich mach der Teil stutzig, wo du durch "new GaugeMeter(document.getElementById...." doch jedesmal ein komplett neues Objekt erzeugst anstatt das bestehende nur upzudaten ? Oder liege ich da falsch ?

So sieht mein entsprechender HTML Absatz aus :

<div class="GaugeMeter" id="drehzahlGauge1"  data-size="355"  data-theme="Green-Gold-Red" data-back="transparent" data-label_color="transparent" data-animate_text_colors="0" data-animate_gauge_colors="1" data-width="20" data-animationstep="0" data-style="Arch" data-stripe="19">

und so die Update Funktion:

source.addEventListener('gaugeValue', function(e) {
  var drehzahl = e.data;
  const meterGauge = new GaugeMeter(document.getElementById("drehzahlGauge1"));
meterGauge.update({ percent: drehzahl });
   }, false);


Hast du da vielleicht eine Idee oder Anregung wie ich alle Text und numerischen Anzeigen unterbinden kann ?
________________________________
Von: Mictronics ***@***.***>
Gesendet: Dienstag, 14. Mai 2024 19:51 Uhr
An: Mictronics/GaugeMeter ***@***.***>
Cc: nobby2k ***@***.***>; Author ***@***.***>
Betreff: Re: [Mictronics/GaugeMeter] Problems with running on IOS / Safari Browser (Issue #18)


No instant idea. I have no access to Apple devices, so can't try. Do you depend on jQuery on your page?
You may try the non-jQuery version: https://github.com/Mictronics/gaugemeter-ts

**Comment by Mictronics** [comment]
Über das CSS des Gaugemeters:
```
  .GaugeMeter SPAN,
  .GaugeMeter B{
    Margin:          0 23%;
    Width:           54%;
    Position:        Absolute;
    Text-align:      Center;
    Display:         Inline-Block;
    Color:           RGBa(0,0,0,.8);
    Font-Weight:     100;
    Font-Family:     "Open Sans", Arial;
    Overflow:        Hidden;
    White-Space:     NoWrap;
    Text-Overflow:   Ellipsis;
  }
```
` Color:           RGBa(0,0,0,.8);` ersetzen durch ` Color:           RGBa(0,0,0,0);`
Siehe Demo CSS Styles: https://www.mictronics.de/gaugemeter/index.html

Die Änderung betrifft dann aber alle Gaugemeter auf eine HTML Seite.
