### ISSUE TITLE
How can I manually layout multiple GaugeMeter widgets?

### ISSUE THREAD

**Issue by saiyn** [Mictronics/GaugeMeter#7]
Hi, I'm a new learner of css and I'm tring using your GaugeMeter and I think it's kind of great project.
But now when I try to layout 4 GaugeMeter widgets, I meet some trouble. I want to let them be 2x2, but now they can just be 1x4. So can this GaugeMeter support manually layout? Could you give me some advice? Thanks in advance.

**Comment by Mictronics** [comment]
```
        <!-- Right middle rover controls -->
        <div id="right-middle-div" style="display: none;">
          <div class="right-middle-div m-2 right-float navigation-background">
            <div class="d-flex flex-row">
              <div class="GaugeMeter" id="gauge-motor1"></div>
              <div class="GaugeMeter" id="gauge-motor3"></div>
            </div>
            <div class="d-flex flex-row">
              <div class="GaugeMeter" id="gauge-motor2"></div>
              <div class="GaugeMeter" id="gauge-motor4"></div>
            </div>
          </div>
        </div>
```

See https://github.com/Mictronics/turtle-rover-control/blob/master/index.html
Styles: https://github.com/Mictronics/turtle-rover-control/blob/master/assets/css/ui-custom.css
