### ISSUE TITLE
Set to a different value than 100%

### ISSUE THREAD

**Issue by maxholgasson** [Mictronics/GaugeMeter#8]
Hi,
I need to display a voltage of a battery. Maximum value is 15V. How can I display e.g 8Volts and draw the according circle?
Either the circle is wrong or it displays 40 (guess it calculates the percentage)  instead of 8 

$("#PreviewGaugeMeter_1").data("percent",voltage);

How can I change there "percent" to a absolute value?

In HTML I tried
`data-showvalue="true" data-min=0 data-total=15 data-used=8`

**Comment by Mictronics** [comment]
See very last example in doc.html:
`<div class="GaugeMeter" id="GaugeMeter" data-label="Volt" data-size="180" data-theme="Red-Gold-Green" data-width="7" data-animate_gauge_colors=false data-animate_text_colors=false data-style="Arch" data-label_color="#FF0000" data-showvalue=true data-total=15 data-used=8></div>`

**Comment by maxholgasson** [comment]
Thanks a lot!! it's working. I made a mistake somewhere obviously
